import dotenv from "dotenv";

dotenv.config();

const { 
  DISCORD_TOKEN, 
  DISCORD_CLIENT_ID, 
  DISCORD_TEST_CHANNEL_ID, 
  DISCORD_CHANNEL_ID,
  DISCORD_DAILY_CHANNEL_ID,
  DISCORD_ROADMAP_CHANNEL_ID,
  ENVIRONMENT 
} = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID || !DISCORD_TEST_CHANNEL_ID || !DISCORD_CHANNEL_ID || !DISCORD_DAILY_CHANNEL_ID || !DISCORD_ROADMAP_CHANNEL_ID || !ENVIRONMENT) {
  throw new Error("Missing environment variables");
}

export const config = {
  ENVIRONMENT,
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  DISCORD_TEST_CHANNEL_ID,
  DISCORD_DAILY_CHANNEL_ID,
  DISCORD_ROADMAP_CHANNEL_ID,
  DISCORD_CHANNEL_ID,
};